/******************************************************************************
 *
 * Project:  Stevens Book - Big Library
 * Purpose:  This is the mother header file for the big library in Steven's
 * 	     book. Functions are defined in differen .c files, I mentioned
 * 	     each one in this file. 
 * Author:   A. H. Ebrahimi <amirhossein183258 at gmail.com>
 *
 ****************************************************************************/

#ifndef __unp_h
#define __unp_h

/* configuration options for curren OS */
/* "./config.h" is generated by configure */
#include "./config.h"

#include <string.h>

#include <sys/socket.h>

#define MAXLINE 4096
#define LISTENQ 1024

/* Shortens all the typecasts of pointer arguments: */
#define SA struct sockaddr

/* Define bzero() as a macro */
#define bzero(ptr, n) memset(ptr, 0, n);

/* sock_ntop.c */
char* sock_ntop(const SA *sa, socklen_t salen);

/* warpunix.c */
void Close(int fd);
ssize_t Read(int fd, void *ptr, size_t nbytes);

/* sock_bind_wild.c */
int sock_bind_wild(int sockfd, int family);
int Sock_bind_wild(int sockfd, int family);

/* sock_cmp_addr.c */
int sock_cmp_addr(const SA *sa1, const SA *sa2, socklen_t salen);

/* sock_cmp_port.c */
int sock_cmp_port(const SA *sa1, const SA *sa2, socklen_t salen);

/* sock_get_port.c */
int sock_get_port(const SA *sa, socklen_t salen);

/* sock_ntop_host.c */
char* sock_ntop_host(const SA *sa, socklen_t salen);
char* Sock_ntop_host(const SA *sa, socklen_t salen);

/* sock_set_addr.c */
void sock_set_addr(SA *sa, socklen_t salen, const void *addr);

/* wrapsock.c */
int Accept(int fd, struct sockaddr *sa, socklen_t *salenptr);
int Socket(int family, int type, int protocol);
void Connect(int fd, const struct sockaddr *sa, socklen_t salen);
void Bind(int fd, const struct sockaddr *sa, socklen_t salen);
void Getsockname(int fd, struct sockaddr *sa, socklen_t *salenptr);
void Listen(int fd, int backlog);
void Write(int fd, void *ptr, size_t nbytes);

/* error.c */
void err_sys(const char *fmt, ...);
void err_quit(const char *fmt, ...);

#endif
