/******************************************************************************
 *
 * Project:  Stevens Book - Big Library
 * Purpose:  This is the mother header file for the big library in Steven's
 * 	     book. Functions are defined in differen .c files, I mentioned
 * 	     each one in this file. 
 * Author:   A. H. Ebrahimi <amirhossein183258 at gmail.com>
 *
 ****************************************************************************/

#ifndef __unp_h
#define __unp_h

/* configuration options for curren OS */
/* "./config.h" is generated by configure */
#include "./config.h"

#include <stdio.h>
#include <string.h>

#include <netdb.h>
#include <sys/socket.h>
#include <sys/types.h> // ssize_t
#include <poll.h>
#include <netinet/in.h>

#define MAXLINE 	4096
#define LISTENQ 	1024
#define BUFFSIZE	8192

#define SERV_MAX_SCTP_STRM 10
#define SERV_MORE_STRMS_SCTP 20

/* Define some port number that can be used for examples */
#define SERV_PORT 9877
#define SERV_PORT_STR "9877"

/* Shortens all the typecasts of pointer arguments: */
#define SA struct sockaddr

/* Define bzero() as a macro */
#define bzero(ptr, n) memset(ptr, 0, n);

/* min and max */
#define min(a, b) ((a) < (b) ? (a) : (b))
#define max(a, b) ((a) > (b) ? (a) : (b))

/* For poll () */
#define INFTIM -1
#define OPEN_MAX 1024 // my system does not have OPEN_MAX macro

/* For signal handlers */
typedef void Sigfunc(int);

/* sock_ntop.c */
char* sock_ntop(const SA *sa, socklen_t salen);
char* Sock_ntop(const SA *sa, socklen_t salen);

/* wrapunix.c */
void Close(int fd);
pid_t Fork(void);
void* Malloc(size_t size);
ssize_t Read(int fd, void *ptr, size_t nbytes);
void Write(int fd, void *ptr, size_t nbytes);

/* sock_bind_wild.c */
int sock_bind_wild(int sockfd, int family);
int Sock_bind_wild(int sockfd, int family);

/* sock_cmp_addr.c */
int sock_cmp_addr(const SA *sa1, const SA *sa2, socklen_t salen);

/* sock_cmp_port.c */
int sock_cmp_port(const SA *sa1, const SA *sa2, socklen_t salen);

/* sock_get_port.c */
int sock_get_port(const SA *sa, socklen_t salen);

/* sock_ntop_host.c */
char* sock_ntop_host(const SA *sa, socklen_t salen);
char* Sock_ntop_host(const SA *sa, socklen_t salen);

/* sock_set_addr.c */
void sock_set_addr(SA *sa, socklen_t salen, const void *addr);

/* sock_set_port.c */
void sock_set_port(SA *sa, socklen_t salen, int port);

/* sock_set_wild.c */
void sock_set_wild(SA *sa, socklen_t salen);

/* readn.c */
ssize_t readn(int fd, void *vptr, size_t n);
ssize_t Readn(int fd, void *ptr, size_t nbytes);

/* writen.c */
ssize_t writen(int fd, const void *vptr, size_t n);
void Writen(int fd, void *ptr, size_t nbytes);

/* readline.c */
/* this implementation is not thread-safe */
ssize_t readline(int fd, void *vptr, size_t maxlen);
ssize_t readlinebuf(void **vptrptr); /* expose readline buffer */
ssize_t Readline(int fd, void *ptr, size_t maxlen);

/* sockfd_to_family.c */
int sockfd_to_family(int sockfd);
int Sockfd_to_family(int sockfd);

/* str_echo.c */
void str_echo(int sockfd);

/* wraplib.c */
const char* Inet_ntop(int family, const void *addrptr, char *strptr, size_t len);
void Inet_pton(int family, const char *strptr, void *addrptr);

/* wrapstdio.c */
void Fclose(FILE *fp);
char* Fgets(char *ptr, int n, FILE *stream);
void Fputs(const char *ptr, FILE *stream);

/* str_cli.c */
void str_cli(FILE *fp, int sockfd);

/* dg_echo.c */
void dg_echo(int sockfd, SA *pcliaddr, socklen_t clilen);

/* dg_cli.c */
void dg_cli(FILE *fp, int sockfd, const SA *pservaddr, socklen_t servlen);

/* sinal.c */
Sigfunc* signal(int signo, Sigfunc *func);
Sigfunc* Signal(int signo, Sigfunc *func);

/* wrapsock.c */
int Accept(int fd, struct sockaddr *sa, socklen_t *salenptr);
void Shutdown(int fd, int how);
int Socket(int family, int type, int protocol);
void Connect(int fd, const struct sockaddr *sa, socklen_t salen);
void Getpeername(int fd, struct sockaddr *sa, socklen_t *salenptr);
void Bind(int fd, const struct sockaddr *sa, socklen_t salen);
void Getsockname(int fd, struct sockaddr *sa, socklen_t *salenptr);
void Getsockopt(int fd, int level, int optname, void *optval, socklen_t *optlenptr);
void Listen(int fd, int backlog);
#ifdef HAVE_POLL
int Poll(struct pollfd *fdarray, unsigned long nfds, int timeout);
#endif
ssize_t Recvfrom(int fd, void *ptr, size_t nbytes, int flags, struct sockaddr *sa, socklen_t *salenptr);
int Select(int nfds, fd_set *readfds, fd_set *writefds, fd_set *exceptfds, struct timeval *timeout);
void Sendto(int fd, const void *ptr, size_t nbytes, int flags, const struct sockaddr *sa, socklen_t salen);
void Setsockopt(int fd, int level, int optname, const void *optval, socklen_t optlen);

/* error.c */
void err_ret(const char *fmt, ...);
void err_sys(const char *fmt, ...);
void err_msg(const char *fmt, ...);
void err_quit(const char *fmt, ...);

/* host_serv.c */
struct addrinfo* host_serv(const char *host, const char *serv, int family, int socktype);

/* tcp_connect.c */
int tcp_connect(const char *host, const char *serv);
int Tcp_connect(const char *host, const char *serv);

/* tcp_client.c */
int tcp_listen(const char *host, const char *serv, socklen_t *addrlenp);
int Tcp_listen(const char *host, const char *serv, socklen_t *addrlenp);

/* udp_client.c */
int udp_client(const char *host, const char *serv, SA **saptr, socklen_t *lenp);
int Udp_client(const char *host, const char *serv, SA **saptr, socklen_t *lenp);

#endif
